**编码**

In [ ]:
t = '''
2007 年重点项目资助情况（按地区统计）
 金额单位：万元

省（直辖 合 计 数理科学部 化学科学部 生命科学部 地球科学部 工程与材料科学部 信息科学部 管理科学部
市）名 项数 金 额 项数 金 额 项数 金 额 项数 金 额 项数 金 额 项数 金 额 项数 金 额 项数 金 额
合 计 373 63,530.00 45 8,600.00 42 7,210.00 113 17,850.00 56 9,500.00 61 10,920.00 42 8,050.00 14 1,400.00
1.北京 145 25,275.00 24 4,740.00 17 3,070.00 41 6,405.00 20 3,435.00 19 3,445.00 19 3,690.00 5 490
2.天津 11 1,744.00 2 360 4 625 1 160 - - 2 330 1 170 1 99
3.河北 3 500 - - - - 1 160 1 160 1 180 - - - -
4.山西 3 540 - - - - - - - - 2 350 1 190 - -
5.辽宁 4 700 - - 1 180 - - - - 2 340 1 180 - -
6.吉林 8 1,337.00 - - 4 710 - - - - 2 360 1 170 1 97
7.黑龙江 1 150 - - - - 1 150 - - - - - - - -
8.上海 46 7,529.00 7 1,285.00 2 305 23 3,620.00 2 365 9 1,570.00 1 180 2 204
9.江苏 28 4,590.00 3 550 2 330 7 1,115.00 9 1,535.00 4 670 1 180 2 210
10.浙江 18 2,975.00 2 320 3 500 5 795 2 340 3 520 2 400 1 100
11.安徽 11 1,960.00 2 380 1 170 2 310 2 335 3 575 1 190 - -
12.福建 8 1,315.00 - - 5 830 1 160 1 165 1 160 - - - -
13.山东 11 1,905.00 1 230 - - 4 620 4 675 2 380 - - - -
14.河南 1 180 - - - - 1 180 - - - - - - - -
15.湖北 15 2,415.00 - - - - 6 1,005.00 4 660 2 350 1 200 2 200
16.湖南 8 1,470.00 1 210 - - 2 310 - - 2 380 3 570 - -
17.广东 19 3,155.00 1 200 1 140 10 1,560.00 4 655 1 220 2 380 - -
18.广西 1 160 - - - - 1 160 - - - - - - - - 
32
省（直辖 合 计 数理科学部 化学科学部 生命科学部 地球科学部 工程与材料科学部 信息科学部 管理科学部
市）名 项数 金 额 项数 金 额 项数 金 额 项数 金 额 项数 金 额 项数 金 额 项数 金 额 项数 金 额
19.四川 9 1,535.00 1 125 1 170 1 160 1 170 2 350 3 560 - -
20.贵州 1 165 - - - - - - 1 165 - - - - - -
21.云南 3 510 - - - - 1 170 1 160 1 180 - - - -
22.陕西 10 1,870.00 1 200 - - 2 320 1 170 1 190 5 990 - -
23.甘肃 4 680 - - 1 180 1 170 2 330 - - - - - -
24.新疆 1 180 - - - - - - 1 180 - - - - - -
25.重庆 4 690 - - - - 2 320 - - 2 370 - - - - 
'''

In [ ]:
t = '''
2006 年国家自然科学基金面上项目资助情况（按地域分布统计）
表 1-11 金额单位：万元
 合 计 自由申请项目 青年基金项目 地区基金项目
省、自治区（州） 项数 金 额 项数 金 额 项数 金 额 项数 金 额
合 计 10271 268,595.00 7429 203,716.00 2429 55,549.00 413 9,330.00
北京 2559 69,552.40 1912 54,622.40 647 14,930.00- -
上海 1068 27,500.70 778 20,991.20 290 6,509.50- -
江苏 718 18,981.00 554 15,130.50 164 3,850.50- -
湖北 634 16,371.80 479 12,844.80 155 3,527.00- -
广东 588 15,588.50 466 12,818.50 122 2,770.00- -
浙江 478 11,974.20 343 8,946.70 135 3,027.50- -
陕西 445 11,547.60 329 8,878.10 116 2,669.50- -
山东 375 9,817.30 294 7,986.80 81 1,830.50- -
辽宁 383 9,809.50 289 7,673.50 94 2,136.00- -
湖南 313 7,838.00 232 6,013.00 81 1,825.00- -
四川 291 7,553.00 227 6,163.00 64 1,390.00- -
安徽 266 7,320.50 205 5,921.00 61 1,399.50- -
天津 275 6,790.00 217 5,551.50 58 1,238.50- -
重庆 247 6,139.50 170 4,450.50 77 1,689.00- -
吉林 225 6,075.00 166 4,722.00 48 1,112.00 11 241
黑龙江 242 6,012.50 181 4,548.00 61 1,464.50- -
福建 176 4,660.00 132 3,660.00 44 1,000.00- -
甘肃 130 3,761.00 96 2,864.00 34 897- -
云南 125 3,097.00 49 1,391.00 13 318 63 1,388.00
河南 101 2,621.50 83 2,199.50 18 422- -
2006 年国家自然科学基金面上项目资助情况（按地域分布统计）
55 国家自然科学基金委员会信息中心编制
 合 计 自由申请项目 青年基金项目 地区基金项目
省、自治区（州） 项数 金 额 项数 金 额 项数 金 额 项数 金 额
河北 95 2,481.00 81 2,159.00 14 322- -
山西 93 2,445.00 73 1,950.00 20 495- -
新疆 87 2,130.00 12 442 7 156 68 1,532.00
江西 83 1,937.00 9 261 8 196 66 1,480.00
广西 76 1,768.00 13 348 4 83 59 1,337.00
贵州 57 1,572.00 25 830 6 150 26 592
内蒙古 68 1,538.00 6 141 3 51 59 1,346.00
海南 33 748 2 61 2 41 29 646
宁夏 19 439 1 23 1 22 17 394
青海 13 310 5 125 1 27 7 158
西藏 8 216- - - - 8 216
'''

In [51]:
temp = '''
2007 年地区科学基金资助情况（按地区统计）
1.北京(共 18 个单位) 39 1,560.00 6 240 4 160 12 480 5 200 6 240 6 240 - -'
'''

In [27]:
#没有标题的话需要手工加上标题
temp = '''
2006 年国家自然科学基金面上项目资助情况（按地域分布统计）
1 北京 3342 200641.30 404 25397.00 277 17893.00 558 32807.00 437 29823.00 521 31325.00 362 21702.00 176 8436.80 607 33257.50
2 上海 2114 122109.90 199 11719.00 200 12866.00 276 16263.00 95 6280.00 256 15351.00 157 9330.00 100 4791.40 831 45509.50
3 江苏 1868 109507.00 171 10069.00 177 11364.00 289 16846.00 173 11582.00 309 18549.00 215 12609.00 73 3487.50 461 25000.50
4 广东 1520 88373.90 95 5523.00 115 7410.00 253 14867.00 128 8659.00 139 8323.00 147 8870.00 61 2901.90 582 31820.00
5 湖北 1201 70840.20 86 5150.00 78 5029.00 250 14716.00 146 9881.00 215 12902.00 98 5806.00 58 2803.20 270 14553.00
6 浙江 898 51951.20 68 3783.00 82 5279.00 155 9095.00 47 3139.00 159 9525.00 109 6498.00 50 2406.20 228 12226.00
7 陕西 867 51870.50 87 5342.00 46 2961.00 105 6266.00 73 4789.00 205 12312.00 167 10240.00 23 1116.00 161 8844.50
8 山东 773 46098.00 43 2492.00 90 5796.00 149 8743.00 126 8378.00 124 7464.00 66 3876.00 16 765.00 159 8584.00
9 四川 643 37951.00 70 4283.00 51 3289.00 90 5284.00 62 4159.00 103 6189.00 78 4718.00 28 1349.00 161 8680.00
10 辽宁 628 36759.50 30 1818.00 81 5194.00 73 4151.00 18 1140.00 192 11530.00 79 4767.00 37 1783.50 118 6376.00
11 湖南 579 33406.50 55 3176.00 31 2007.00 48 2825.00 30 1923.00 154 9174.00 82 4794.00 27 1290.00 152 8217.50
12 天津 478 28043.00 43 2519.00 85 5486.00 46 2711.00 14 905.00 109 6522.00 60 3522.00 24 1154.00 97 5224.00
13 安徽 461 28009.00 95 6013.00 53 3412.00 59 3479.00 56 3889.00 71 4278.00 39 2375.00 21 1000.50 67 3562.50
14 黑龙江 472 27398.00 34 2027.00 18 1177.00 80 4555.00 14 851.00 154 9303.00 57 3401.00 26 1270.00 89 4814.00
15 福建 407 23840.00 28 1552.00 76 4912.00 83 4892.00 40 2636.00 39 2325.00 34 1903.00 14 673.00 93 4947.00
16 重庆 396 22912.00 15 840.00 19 1219.00 75 4479.00 14 904.00 84 5068.00 36 2093.00 6 291.00 147 8018.00
17 吉林 374 22775.00 38 2252.00 75 4837.00 65 3860.00 48 3241.00 63 3754.00 37 2295.00 2 97.00 46 2439.00
18 河南 276 15874.00 22 1149.00 34 2193.00 40 2176.00 28 1801.00 53 3168.00 32 1690.00 1 48.00 66 3649.00
19 甘肃 196 12211.00 26 1596.00 33 2106.00 32 1847.00 65 4393.00 21 1266.00 4 232.00 2 100.00 13 671.00
20 河北 150 8759.00 9 500.00 8 515.00 28 1671.00 3 204.00 53 3163.00 17 1013.00 2 94.00 30 1599.00
'''

In [52]:
lt = temp.split('\n')

#two: 2007 年地区科学基金资助情况（按地区统计）
two = lt[1].split(" ")
year = two[0]
Type = two[1]

'''
year = ''
Type = ''
'''

city = []
num = []
money = []
lyear = []
ltype = []

for item in lt:
    
    
    try:
        lt_item = item.split(' ')
        inform = [lt_item[i] for i in range(4)]
        '''
        20 河北 150 8759.00 9 500.00 8 515.00 28 1671.00 3 204.00 53 3163.00 17 1013.00 2 94.00 30 1599.00
         如果是这种形式，需要使用下面的代码:
        '''
        inform.pop(0)
        
        
        #广 西 73 1,368.00 5 102 5 86 41 743 3 49 10 218 7 136 2 34 先忽略这种情况
        #河南 101 2,621.50 83 2,199.50 18 422- -
        #19.四川 9 1,535.00 1 125 1 170 1 160 1 170 2 350 3 560 - -        
        if "." in inform[0]:
            inform[0] = inform[0].split('.')[-1]
        
        for i in ['北京','上海','江苏','湖北','浙江']:
            if (i in inform[0]) and ("大学" not in inform[0]):
        #出错的人的信息不能被保存到列表，否则会被写入文件影响结果
                lyear.append(year)
                ltype.append(Type)
                city.append(inform[0])
                num.append(inform[1])
                money.append(inform[2])
                if len(city)==5:
                    print("-----------------------------------data_ok--------------------------------------------------" )
    

        
    except:
        print('error__year:{} Type:{}'.format(year,Type))

error__year:2007 Type:年地区科学基金资助情况（按地区统计）
error__year:2007 Type:年地区科学基金资助情况（按地区统计）
error__year:2007 Type:年地区科学基金资助情况（按地区统计）

In [53]:
city

[]

In [47]:
"大学" not in inform[0]

True

In [55]:
inform

['18', '个单位)', '39']

In [34]:
from openpyxl import load_workbook

#列表写入excel文件
            #填写要固定的列
def write(index,ws,lt):
    for i in range(len(lt)):
        ws.cell(2+i,index).value = lt[i]
        print(i,end=' ')
            #选择填入某行的单元格
            
            
#处理文件
path = 'D:\\paper\\wang\\广东联合基金\\资助项目统计\\raw.xlsx'  #填写路径
wb = load_workbook(path)
ws1 = wb["Sheet1"]   #填写工作表名字

#填写sheet1
write(1,ws1,lyear)
write(2,ws1,ltype)
write(3,ws1,city)
write(4,ws1,num)
write(5,ws1,money)
wb.save(path)
print("write_Sheet1_ok")

0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 write_Sheet1_ok