In [1]:
import pandas as pd
import numpy as np

In [3]:
# 导入调查问卷
df = pd.read_csv(r'D:\file\o\队长\满意度\队员对队长\9月\队员对队长满意度问卷结果提取.csv',encoding='gbk')
df.head()

,region,city_name,city_id,product_level2_name,driver_id,driver_name,team_org_id,team_org_name,leader_driver_id,leader_name,manager_id,manager_name,question01,question02,question03,question04,question05,question06,score
0,西南区域,昆明市,19,专车,580542284884877,罗伟,245144,太华4组,564288717725696,周翔,11714,肖瑞,知道,20.0,20.0,20.0,10.0,30.0,100
1,西南区域,昆明市,19,专车,580542284884877,罗伟,245144,太华4组,564288717725696,周翔,11712,杜佳,知道,20.0,20.0,20.0,10.0,30.0,100
2,西南区域,昆明市,19,优享,567950147079450,何虎熊,180858,传奇优享·对公六队,580542341825176,洪云,897194813,管波,知道,16.0,16.0,16.0,10.0,24.0,82
3,西南区域,昆明市,19,快车,565456205907948,程金华,418781,西山A1-雷,580542471999296,李立,282438,陈大卫,知道,20.0,20.0,20.0,10.0,30.0,100
4,西南区域,昆明市,19,快车,580544642384455,段永平,398155,官渡B04-成勇,580543491837657,成勇,282440,李玉芬,知道,20.0,20.0,20.0,10.0,30.0,100

## 改变业务线（快车，优享，D1）跑3次

In [4]:
# 改变业务线
#df = df[df['product_level2_name']=='快车']
df = df[df['product_level2_name']=='优享']
#df = df[df['product_level2_name']=='D1']
df.head()

,region,city_name,city_id,product_level2_name,driver_id,driver_name,team_org_id,team_org_name,leader_driver_id,leader_name,manager_id,manager_name,question01,question02,question03,question04,question05,question06,score
2,西南区域,昆明市,19,优享,567950147079450,何虎熊,180858,传奇优享·对公六队,580542341825176,洪云,897194813,管波,知道,16.0,16.0,16.0,10.0,24.0,82
16,西南区域,重庆市,18,优享,564509624763765,曹洋,513382,余大伦-朝天门14组,580542222629413,余大伦,901182760,廖芷薇,知道,20.0,20.0,20.0,10.0,30.0,100
84,中南区域,南昌市,38,优享,567949986320636,万少平,307778,优享认证永鸿小队,563736397938689,兰赟,24936,邓洪佳,知道,20.0,20.0,20.0,10.0,30.0,100
91,中南区域,南昌市,38,优享,565162997191799,余海奎,307778,优享认证永鸿小队,563736397938689,兰赟,24936,邓洪佳,知道,20.0,20.0,20.0,10.0,30.0,100
103,中南区域,南昌市,38,优享,580542140720573,李建国,307778,优享认证永鸿小队,563736397938689,兰赟,24936,邓洪佳,知道,20.0,20.0,20.0,10.0,30.0,100

In [5]:
# 0 看看
df_should = df[['driver_id','region','city_name','product_level2_name','leader_driver_id','leader_name']]
df_should.head()

,driver_id,region,city_name,product_level2_name,leader_driver_id,leader_name
2,567950147079450,西南区域,昆明市,优享,580542341825176,洪云
16,564509624763765,西南区域,重庆市,优享,580542222629413,余大伦
84,567949986320636,中南区域,南昌市,优享,563736397938689,兰赟
91,565162997191799,中南区域,南昌市,优享,563736397938689,兰赟
103,580542140720573,中南区域,南昌市,优享,563736397938689,兰赟

In [71]:
###去重 赋0分

In [6]:
# 1.1 按照第1题分表（第1题：您是否知道如何联系到您的队长）
df_no   = df[df['question01']=='不知道']
df_know = df[df['question01']=='知道']
print('不知道的问卷 ',df_no.shape[0])
print('知道的问卷   ',df_know.shape[0])
print('总问卷       ',df.shape[0])
# 1.2 不知道的队员赋分
df_no.loc[:,'态度']=0
df_no.loc[:,'通知']=0
df_no.loc[:,'反馈']=0
df_no.loc[:,'团队']=0
df_no.loc[:,'整体']=0
df_no.loc[:,'score']=0
# 1.3 知道的队员赋分
df_know.loc[:,'态度']=df_know['question02']
df_know.loc[:,'通知']=df_know['question03']
df_know.loc[:,'反馈']=df_know['question04']
df_know.loc[:,'团队']=df_know['question05']
df_know.loc[:,'整体']=df_know['question06']
# 1.4 不知道与知道的结果合并&保留分数最高项去重
df_all = pd.concat([df_no,df_know])
df_all = df_all.sort_values(by=['driver_id','score'],ascending=False)
df_all = df_all.drop_duplicates('driver_id',keep='first')
print('\n有效问卷数   ',df_all.shape[0])

不知道的问卷  171
知道的问卷    4566
总问卷        4737

有效问卷数    4728

C:\Users\shenyajun_i\Anaconda3\lib\site-packages\pandas\core\indexing.py:1597: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
C:\Users\shenyajun_i\Anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\shenyajun_i\Anaconda3\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

### 知晓人数 总回收数

In [74]:
# 2.1 总回收数
#队长
df_sfid   = df_all.groupby(['leader_driver_id'],as_index=False)['driver_id'].count()
df_sfid.columns  =['队长ID','回收数']
#城市
df_cityid = df_all.groupby(['region','city_name'],as_index=False)['driver_id'].count()
df_cityid.columns=['大区','城市','回收数']
#大区
df_areaid = df_all.groupby(['region'],as_index=False)['driver_id'].count()
df_areaid.columns=['大区','回收数']


# 2.2 知晓人数
df_know_final = df_all[df_all['question01']=='知道']
#队长
df_sf_zx   = df_know_final.groupby('leader_driver_id',as_index=False)['driver_id'].count()
df_sf_zx.columns  =['队长ID','知晓人数']
#城市
df_city_zx = df_know_final.groupby(['region','city_name'],as_index=False)['driver_id'].count()
df_city_zx.columns=['大区','城市','知晓人数']
#大区
df_area_zx = df_know_final.groupby('region',as_index=False)['driver_id'].count()
df_area_zx.columns=['大区','知晓人数']


# 2.3 以上两表合并
#队长
df_sf_left   = pd.merge(df_sfid,df_sf_zx,left_on ='队长ID',right_on='队长ID',how='left')
#城市
df_city_left = pd.merge(df_cityid,df_city_zx,left_on =['大区','城市'],right_on=['大区','城市'],how='left')
#大区
df_area_left = pd.merge(df_areaid,df_area_zx,left_on ='大区',right_on='大区',how='left')

### 各题目均值 知晓率 得分

In [1]:
# 3.1 转换字符类型
df_know_final[['态度', '通知','反馈', '团队','整体','score']]=df_know_final[['态度', '通知','反馈', '团队','整体','score']].astype(float)

# 3.2 均值
#队长
df_sf_right  = df_know_final.groupby(['leader_driver_id'],as_index=False)[['态度', '通知','反馈', '团队','整体','score']].mean()
#城市
df_city_right= df_know_final.groupby(['region','city_name'],as_index=False)[['态度', '通知','反馈', '团队','整体','score']].mean()
#大区
df_area_right= df_know_final.groupby(['region'],as_index=False)[['态度', '通知','反馈', '团队','整体','score']].mean()

# 3.3 两表合并(左表-回收/知晓 + 右表-得分)
#队长
df_sf_output   =pd.merge(df_sf_left,df_sf_right,left_on='队长ID',right_on='leader_driver_id',how='left')
#城市
df_city_output =pd.merge(df_city_left,df_city_right,left_on=['大区','城市'],right_on=['region','city_name'],how='left')
#大区
df_area_output =pd.merge(df_area_left,df_area_right,left_on='大区',right_on='region',how='left')

# 3.4 知晓率
#队长
df_sf_output['知晓率']      =df_sf_output['知晓人数']/df_sf_output['回收数']
df_sf_output['不知晓人数']  =df_sf_output['回收数']-df_sf_output['知晓人数']
df_sf_output['得分']        =df_sf_output['score']*df_sf_output['知晓率']
#城市
df_city_output['知晓率']    =df_city_output['知晓人数']/df_city_output['回收数']
df_city_output['不知晓人数']=df_city_output['回收数']-df_city_output['知晓人数']
df_city_output['得分']      =df_city_output['score']*df_city_output['知晓率']
#大区
df_area_output['知晓率']    =df_area_output['知晓人数']/df_area_output['回收数']
df_area_output['不知晓人数']=df_area_output['回收数']-df_area_output['知晓人数']
df_area_output['得分']      =df_area_output['score']*df_area_output['知晓率']

NameError: name 'df_know_final' is not defined

### 排版&汇总

In [78]:
# 4.1 排版
#队长
list_sf=['队长ID','回收数','知晓人数','不知晓人数','知晓率','态度', '通知','反馈', '团队','整体','score','得分']
df_sf_output=df_sf_output[list_sf].fillna(0)
#城市
list_city=['大区','城市','回收数','知晓人数','不知晓人数','知晓率','态度', '通知','反馈', '团队','整体','score','得分']
df_city_order = df_city_output[list_city].fillna(0).sort_values('得分',ascending=False)
    #对分数进行排序并进行排序
df_city_order['排名']=df_city_order['得分'].rank(ascending=False,method='min')
#大区
df_area_city = df_should[['region','city_name']].drop_duplicates().groupby('region',as_index=False).count()
df_area_city.columns=['大区','城市数量']
df_area_city1 = pd.merge(df_area_output,df_area_city,left_on = '大区',right_on='大区')
#多了1个汇总行，但只计算了这4个字段（可以直接汇总的）
df_area_city1.loc['汇总']=df_area_city1[['回收数','知晓人数','不知晓人数','城市数量']].sum() 
df_area_city1.loc['汇总','大区']='全国'
df_area_city1.loc['汇总','region']='全国'
#不可以直接汇总，需要汇总所有问卷的分数 + 计算知晓率 和 得分
df_area_city1.loc['汇总',['态度', '通知','反馈', '团队','整体','score']]=df_know_final[['态度', '通知','反馈', '团队','整体','score']].mean()
df_area_city1.loc['汇总','知晓率']=df_area_city1.loc['汇总','知晓人数']/df_area_city1.loc['汇总','回收数']
df_area_city1.loc['汇总','得分']=df_area_city1.loc['汇总','score']*df_area_city1.loc['汇总','知晓率']


# 4.2 更改列名
df_sf_output = df_sf_output.rename(columns={'score':'知晓得分','得分':'最终得分'})
df_city_order = df_city_order.rename(columns={'score':'知晓得分','得分':'最终得分'})
df_area_city1 = df_area_city1.rename(columns={'score':'知晓得分','得分':'最终得分'})

## 写出

In [79]:
#写入Excel&保存
writer = pd.ExcelWriter('H:/work/满意度hyw/9月队员对队长满意度/9月队员对队长-快车1.xlsx')
df_sf_output.to_excel(writer,'队长',index=False)
df_area_city1.to_excel(writer,'区域',index=False)
df_city_order.to_excel(writer,'城市',index=False)
df_all.to_excel(writer,'明细',index=False)
writer.save()